### PR TITLE
checkpoint: verify checkpoint when resume from checkpoint

### LINKED ISSUE #302: Avoid reusing checkpoint when backend or table ID changed
When switching from TiDB backend to Local/Importer backend, the recorded checksum values become invalid. This would lead to strange checksum error. 

We should make the checkpoint invalid if the backend is changed (and probably other parameters too).

### LINKED ISSUE #327: misleading log ("user terminated") may be report when the import is abnormal
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    see <https://asktug.com/t/topic/34941>

2. What did you expect to see?

3. What did you see instead?

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
       v4.0.0
        ```
        

5. Operation logs

    ```
    [2020/06/02 15:28:14.249 +08:00] [INFO] [restore.go:266] ["user terminated"] [step=2] [error="restore table `pay`.`pay_purchase` failed: rpc error: code = Canceled desc = Cancelled"]
    ```

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 

- when reuses checkpoints, if some config has change, return errors. Will check following fields
  -  tikv-importer.backend
  -  tikv-importer.addr (if backend == 'importer')
  -  tikv-importer.sorted-kv-dir (if backend == 'local')
  - mydumper.data-source-dir
  - tidb.host && tidb.port
  - tidb.pd-addr

User can force to execute by set `check-requirements = true`, but if `tikv-importer.backend` is different, will always return erros even with this setting.

close #302 
also close #327 since it's an one-line small change.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
> tikv-importer.addr (if backend == 'importer')

we should also compare `tikv-importer.sorted-kv-dir` if backend is local

**Comment by glorv** [comment]
> > tikv-importer.addr (if backend == 'importer')
> 
> we should also compare `tikv-importer.sorted-kv-dir` if backend is local

updated

File: lightning/checkpoints/checkpoints.go [hunk 1]
```diff
@@ -329,8 +333,61 @@ type DestroyedTableCheckpoint struct {
 	MaxEngineID int32
 }
 
+type TaskCheckpoint struct {
+	TaskId       int64
+	SourceDir    string
+	Backend      string
+	ImporterAddr string
+	TidbAddr     string
```
Comment (kennytm) [inline lightning/checkpoints/checkpoints.go:341]: how about store the host and port in separate fields 🤷 

```suggestion
	TiDBHost     string
	TiDBPort     uint16
```

File: lightning/checkpoints/checkpoints.go [hunk 2]
```diff
@@ -400,6 +462,22 @@ func NewMySQLCheckpointsDB(ctx context.Context, db *sql.DB, schemaName string, t
 		return nil, errors.Trace(err)
 	}
 
+	err = sql.Exec(ctx, "create task checkpoints table", fmt.Sprintf(`
+		CREATE TABLE IF NOT EXISTS %s.%s (
+			id int NOT NULL PRIMARY KEY,
```
Comment (kennytm) [inline lightning/checkpoints/checkpoints.go:467]:
```suggestion
			id tinyint(1) PRIMARY KEY,
```

File: lightning/checkpoints/checkpoints.go [hunk 3]
```diff
@@ -465,12 +543,31 @@ func NewMySQLCheckpointsDB(ctx context.Context, db *sql.DB, schemaName string, t
...
+
 	// We can have at most 65535 placeholders https://stackoverflow.com/q/4922345/
 	// Since this step is not performance critical, we just insert the rows one-by-one.
-
 	s := common.SQLWithRetry{DB: cpdb.db, Logger: log.L()}
 	err := s.Transact(ctx, "insert checkpoints", func(c context.Context, tx *sql.Tx) error {
+		taskStmt, err := tx.PrepareContext(c, fmt.Sprintf(`
+			INSERT INTO %s.%s (id, task_id, source_dir, backend, importer_addr, tidb_addr, pd_addr, sorted_kv_dir) VALUES (1, ?, ?, ?, ?, ?, ?, ?)
+			ON DUPLICATE KEY UPDATE task_id = VALUES(task_id), source_dir = VALUES(source_dir), backend = VALUES(backend), importer_addr = VALUES(importer_addr), 
+			tidb_addr = VALUES(tidb_addr), pd_addr = VALUES(pd_addr), sorted_kv_dir = VALUES(sorted_kv_dir);
```
Comment (kennytm) [inline lightning/checkpoints/checkpoints.go:559]:
```suggestion
			REPLACE INTO %s.%s (id, task_id, source_dir, backend, importer_addr, tidb_addr, pd_addr, sorted_kv_dir) VALUES (1, ?, ?, ?, ?, ?, ?, ?);
```

File: lightning/checkpoints/checkpoints.go [hunk 4]
```diff
@@ -329,8 +332,60 @@ type DestroyedTableCheckpoint struct {
...
+		}
+	}
+
+	return nil
+}
+
 type CheckpointsDB interface {
-	Initialize(ctx context.Context, dbInfo map[string]*TidbDBInfo) error
+	Initialize(ctx context.Context, cfg *config.Config, dbInfo map[string]*TidbDBInfo) error
+	getTaskCheckpoint(ctx context.Context) (*TaskCheckpoint, error)
```
Comment (kennytm) [inline lightning/checkpoints/checkpoints.go:388]: i suggest we either change the interface to 

```suggestion
	Initialize(ctx context.Context, dbInfo map[string]*TidbDBInfo) (*TaskCheckpoint, error)
```

or make `getTaskCheckpoint` public so it is reachable from `restore.go`

```suggestion
	Initialize(ctx context.Context, dbInfo map[string]*TidbDBInfo) error
 	TaskCheckpoint(ctx context.Context) (*TaskCheckpoint, error)
```

in any case, perform `verifyCheckpoint` outside of `Initialize`.

Comment (glorv) [reply lightning/checkpoints/checkpoints.go]: I moved this check codes in `NewRestoreController` right after `OpenCheckpointDB`

File: lightning/checkpoints/checkpoints.go [hunk 5]
```diff
@@ -508,6 +558,31 @@ func (cpdb *MySQLCheckpointsDB) Initialize(ctx context.Context, dbInfo map[strin
...
+		"SELECT task_id, source_dir, backend, importer_addr, tidb_host, tidb_port, pd_addr, sorted_kv_dir FROM %s.%s WHERE id = 1",
+		cpdb.schema, CheckpointTableNameTask,
+	)
+	taskCp := &TaskCheckpoint{}
+	err := s.QueryRow(ctx, "fetch task checkpoint", taskQuery, &taskCp.TaskId, &taskCp.SourceDir, &taskCp.Backend,
+		&taskCp.ImporterAddr, &taskCp.TiDBHost, &taskCp.TiDBPort, &taskCp.PdAddr, &taskCp.SortedKVDir)
+
+	if err != nil {
+		// if task checkpoint is empty, return nil
+		if strings.Contains(err.Error(), sql.ErrNoRows.Error()) {
```
Comment (kennytm) [inline lightning/checkpoints/checkpoints.go:577]: can we check using `errors.Cause(err) == sql.ErrNoRows`?

**Review by kennytm — COMMENTED** [review]
rest LGTM

**Comment by kennytm** [comment]
lgtm

File: lightning/restore/restore.go [hunk 6]
```diff
@@ -343,6 +351,47 @@ func (rc *RestoreController) restoreSchema(ctx context.Context) error {
...
+
+		if cfg.TiDB.Host != taskCp.TiDBHost {
+			return errors.Errorf(errorFmt, "tidb.host", cfg.TiDB.Host, taskCp.TiDBHost)
+		}
+
+		if cfg.TiDB.Port != taskCp.TiDBPort {
+			return errors.Errorf(errorFmt, "tidb.port", cfg.TiDB.Port, taskCp.TiDBPort)
+		}
+
+		if cfg.TiDB.PdAddr != taskCp.PdAddr {
```
Comment (3pointer) [inline lightning/restore/restore.go:387]: `PdAddr` can be nil, maybe let it pass when `cfg.TiDB.PdAddr` or `taskCp.PdAddr` is nil.

**Comment by 3pointer** [comment]
Rest LGTM

File: lightning/restore/restore.go (hunk 6 above)
Comment (glorv) [reply lightning/restore/restore.go:387]: I think there is no reasonable reason for user to change pdAddr to empty when resume from checkpoint? And since `cfg.TiDB.PdAddr` maybe impact the target cluster addr, so I think this check is necessary, and user can still skip this check by set `check-requirements = false`

**Review by 3pointer — APPROVED** [review]
