### PR TITLE
backend: fix auto random default value for primary key

### LINKED ISSUE #444: Local backend is unable to import auto random sql files without auto random key data
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Create a table with auto_random primary key. Import data from sql files without primary key data via local backend.
```sql
> create table t (id bigint unsigned NOT NULL /*T![auto_rand] AUTO_RANDOM(5) */ primary key, a varchar(100));
```
data.sql
```sql
insert into t (a) values("hello"),("hi");
```

2. What did you expect to see?
Import successfully

3. What did you see instead?
Import failed
```
Error: restore table `test`.`t_autorandom` failed: checksum mismatched remote vs local => (checksum: 742543142478472942 vs 8779592692293909936) (total_kvs: 1 vs 1000) (total_bytes:485 vs 485000)
tidb lightning encountered error:  restore table `test`.`t_autorandom` failed: checksum mismatched remote vs local => (checksum: 742543142478472942 vs 8779592692293909936) (total_kvs: 1 vs 1000) (total_bytes:485 vs 485000)
```

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        ./bin/tidb-lightning -V
       Release Version: v4.0.8-3-geb609ec-dev
       Git Commit Hash: eb609ecfa6ca38205084843f2341cfc79cd30414
       Git Branch: master
       UTC Build Time: 2020-11-04 06:37:13
       Go Version: go version go1.15.1 darwin/amd64
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        v4.0.7
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.7
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Set default auto random value for primary key column field if valus is missing.

close #444 
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

Release Note
- support set a default value for auto random primary key for local/importer backend

### CODE REVIEW

File: lightning/backend/sql2kv.go [hunk 1]
```diff
@@ -37,17 +41,37 @@ type tableKVEncoder struct {
...
+	if tbl.Meta().PKIsHandle && tbl.Meta().ContainsAutoRandomBits() {
+		for _, col := range tbl.Cols() {
+			if mysql.HasPriKeyFlag(col.Flag) {
+				typeBitsLength := uint64(mysql.DefaultLengthOfMysqlTypes[col.Tp] * 8)
+				incrementalBits := typeBitsLength - tbl.Meta().AutoRandomBits
+				hasSignBit := !mysql.HasUnsignedFlag(col.Flag)
+				if hasSignBit {
+					incrementalBits -= 1
+				}
+				autoRandomBits = rand.New(rand.NewSource(chunk.Chunk.Offset)).Int63n(1<<tbl.Meta().AutoRandomBits) << incrementalBits
```
Comment (kennytm) [inline lightning/backend/sql2kv.go:65]: `chunk.Chunk.Offset` is not a good seed since most of the time it is always 0.

File: lightning/backend/backend.go [hunk 2]
```diff
@@ -104,7 +106,7 @@ type AbstractBackend interface {
 	ShouldPostProcess() bool
 
 	// NewEncoder creates an encoder of a TiDB table.
-	NewEncoder(tbl table.Table, options *SessionOptions) Encoder
+	NewEncoder(tbl table.Table, options *SessionOptions, chunk *checkpoints.ChunkCheckpoint) Encoder
```
Comment (kennytm) [inline lightning/backend/backend.go:109]: can we make the auto-rand seed as part of the `SessionOptions`? this should reduce a lot of diff.

File: tests/auto_random_default/data/auto_random.t.1.sql [hunk 3]
```diff
@@ -0,0 +1,5 @@
+/*!40103 SET TIME_ZONE='+00:00' */;
```
Comment (kennytm) [inline tests/auto_random_default/data/auto_random.t.1.sql:1]: can we also add an `auto_random.t.2.sql` to verify the behavior of auto-random bits?

(and `select count(distinct id >> 58) from t` should return 2.)
(no need to test it on TiDB backend due to possibility of failure as the RNG is not controllable on TiDB.)

**Review by kennytm — COMMENTED** [review]
rest LGTM

**Review by overvenus — COMMENTED** [review]
LGTM

**Review by kennytm — APPROVED** [review]
