### PR TITLE
*: replace context.Backend with app context

### LINKED ISSUE #462: lightning warning repeatedly without exit while certs are wrong
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
tidb-lightning.toml with wrong certs in security section
```
tidb.tls = "false"
```

2. What did you expect to see?
Import successfully and no error

3. What did you see instead?
lightning output warning repeatedly, and it can't be stopped by ctrl-c
```
root@agent:/data1/cy/src/tidb-lightning# ./bin/tidb-lightning -c tidb-lightning.toml
Verbose debug logs will be written to tidb-lightning.log

[2020/11/10 07:04:59.497 +00:00] [INFO] [client.go:166] ["[pd] create pd client with endpoints"] [pd-address="[db-pd.tidb1326054958621003776.svc:2379]"]
[2020/11/10 07:04:59.505 +00:00] [WARN] [base_client.go:180] ["[pd] failed to get cluster id"] [url=http://db-pd.tidb1326054958621003776.svc:2379] [error="[PD:client:ErrClientGetMember]error:rpc error: code = Unavailable desc = connection error: desc = \"transport: authen
tication handshake failed: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"TiDB CA\\\")\" target:db-pd.tidb1326054958621003776.svc:2379 status:TRANSIENT_FA
ILURE"]
[2020/11/10 07:05:00.505 +00:00] [WARN] [base_client.go:180] ["[pd] failed to get cluster id"] [url=http://db-pd.tidb1326054958621003776.svc:2379] [error="[PD:client:ErrClientGetMember]error:rpc error: code = Unavailable desc = connection error: desc = \"transport: authen
tication handshake failed: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"TiDB CA\\\")\" target:db-pd.tidb1326054958621003776.svc:2379 status:TRANSIENT_FA
ILURE"]
[2020/11/10 07:05:01.506 +00:00] [WARN] [base_client.go:180] ["[pd] failed to get cluster id"] [url=http://db-pd.tidb1326054958621003776.svc:2379] [error="[PD:client:ErrClientGetMember]error:rpc error: code = Unavailable desc = connection error: desc = \"transport: authen
tication handshake failed: x509: certificate signed by unknown authority (possibly because of \\\"crypto/rsa: verification error\\\" while trying to verify candidate authority certificate \\\"TiDB CA\\\")\" target:db-pd.tidb1326054958621003776.svc:2379 status:TRANSIENT_FA
ILURE"]
```

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        ./bin/tidb-lightning -V
       Release Version: v4.0.8-10-g51d0e7b
       Git Commit Hash: 51d0e7bf56f7b5007fbdb310be7b7ef5e68ffcc9
       Git Branch: master
       UTC Build Time: 2020-11-10 04:38:28
       Go Version: go version go1.13.15 linux/amd64
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        (paste TiKV version here)
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
```
[lightning]

status-addr = ":8289"

server-mode = false


index-concurrency = 2
table-concurrency = 6

level = "info"
file = "tidb-lightning.log"
max-size = 128 # MB
max-days = 28
max-backups = 14

[security]
ca-path = "2768/client-ca.crt"
cert-path = "2768/client-tls.crt"
key-path = "2768/client-tls.key"

[checkpoint]
enable = true
schema = "tidb_lightning_checkpoint"
driver = "file"

[tikv-importer]
backend = "local"
addr = "127.0.0.1:8287"
sorted-kv-dir = "/data2/sortkv"

[mydumper]
read-block-size = 65536 # Byte (default = 64 KB)

batch-import-ratio = 0.75

data-source-dir = "s3://cy-massive-data/uuid_1t_csv?region=us-east-1"
no-schema=true

case-sensitive = false

strict-format = false


filter = ['*.*', '!mysql.*', '!sys.*', '!INFORMATION_SCHEMA.*', '!PERFORMANCE_SCHEMA.*', '!METRICS_SCHEMA.*', '!INSPECTION_SCHEMA.*']

[mydumper.csv]
separator = ','
delimiter = '"'
header = false
not-null = false
null = '\N'
backslash-escape = true
trim-last-separator = false


[tidb]
host = "db-tidb.tidb1326054958621003776.svc"
port = 4000
user = "root"
password = "12345678"
status-port = 10080
pd-addr = "db-pd.tidb1326054958621003776.svc:2379"
log-level = "error"


tls = "false"

build-stats-concurrency = 20
distsql-scan-concurrency = 100
index-serial-scan-concurrency = 20
checksum-table-concurrency = 16

[tidb.security]
ca-path = "2768/client-ca.crt"
cert-path = "2768/client-tls.crt"
key-path = "2768/client-tls.key"

[post-restore]
checksum = "required"
analyze = "optional"
level-1-compact = false
compact = false

[cron]
switch-mode = "5m"
log-progress = "5m"
```
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Replace some usage of `context.Backend` or `context.TODO` with lightning app context. So we can stop some sub task more quickly.

close #462 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
~LGTM~

File: lightning/common/security.go [hunk 1]
```diff
@@ -146,7 +147,11 @@ func (tc *TLS) WrapListener(l net.Listener) net.Listener {
 
 // GetJSON obtains JSON result with the HTTP GET method.
 func (tc *TLS) GetJSON(path string, v interface{}) error {
-	return GetJSON(tc.client, tc.url+path, v)
+	return tc.GetJSONWithContext(context.TODO(), path, v)
```
Comment (kennytm) [inline lightning/common/security.go:150]:
```suggestion
	return tc.GetJSONWithContext(context.Background(), path, v)
```

i don't think you could use other context here, so no TODO. (or just remove the entire non-Context function)

**Review by kennytm — COMMENTED** [review]
rest LGTM

File: cmd/tidb-lightning-ctl/main.go [hunk 2]
```diff
@@ -71,11 +71,13 @@ func run() error {
 		fsUsage = fs.Usage
 	}))
 
+	ctx := context.Background()
```
Comment (overvenus) [inline cmd/tidb-lightning-ctl/main.go:74]: Can we cancel the context by receiving a signal?

Comment (glorv) [reply cmd/tidb-lightning-ctl/main.go:74]: Seems not currently. Because all the actions lightning-ctl provide should be processed quite fast, there is no need to cancel it.

Comment (lance6716) [reply cmd/tidb-lightning-ctl/main.go:74]: > Can we cancel the context by receiving a signal?

default action to usual signal could stop `tidb-lightning-ctl`, not graceful but I think that's OK.

**Review by kennytm — APPROVED** [review]
