### PR TITLE
restore: better estimate task remain time progress log

### LINKED ISSUE #303: Progress is inaccurate (overestimating time taken) when reusing checkpoint
Repro steps:

1. Import some large database, long enough for the progress log to appear
2. Ctrl+C before all tables are written
3. Resume from checkpoint
4. Note that the remaining time is very long, as it includes those files already processed.

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Skip chunks that are finished restore when calculate estimate remain chunks numbers.  This can help make progress log a little more accurate. 

NOTE: the currently progress log do not consider the extra time needed in the import phase, so the estimate reamin time should still be lower than actual time.

maybe close #303

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
LGTM

File: lightning/restore/restore.go [hunk 1]
```diff
@@ -403,15 +404,37 @@ func verifyCheckpoint(cfg *config.Config, taskCp *TaskCheckpoint) error {
...
 			for _, fileMeta := range tableMeta.DataFiles {
+				if cnt, ok := fileChunks[fileMeta.FileMeta.Path]; ok {
+					estimatedChunkCount += cnt
+					continue
+				}
 				if fileMeta.FileMeta.Type == mydump.SourceTypeCSV {
 					cfg := rc.cfg.Mydumper
 					if fileMeta.Size > cfg.MaxRegionSize && cfg.StrictFormat && !cfg.CSV.Header {
-						estimatedChunkCount += int(fileMeta.Size / cfg.MaxRegionSize)
+						estimatedChunkCount += math.Round(float64(fileMeta.Size) / float64(cfg.MaxRegionSize))
```
Comment (overvenus) [inline lightning/restore/restore.go:437]: Does it match how we split files?

Comment (glorv) [reply lightning/restore/restore.go:437]: yes, we split csv file by  `max-region-size` config. Each chunk maybe a little bigger than `max-region-size` since we always split chunk at the end of one line.

**Review by 3pointer — APPROVED** [review]
LGTM
