### PR TITLE
mydumper: verify file routing config

### LINKED ISSUE #469: File routing configuration should check before starting import
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
Dumpling data with -S $sql. Import data w/ a configuration without path or pattern.

2. What did you expect to see?
Lightning failed at the very beginning

3. What did you see instead?
Lightning failed while importing metadata file

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        # ./bin/tidb-lightning -V
        Release Version: v4.0.8-13-g963829f-dev
        Git Commit Hash: 963829fd54f16ba135790bc8bde4b8c2d48fb1aa
        Git Branch: master
        UTC Build Time: 2020-11-11 07:50:52
        Go Version: go version go1.13.15 linux/amd64        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        (paste TiKV version here)
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
- Add checksum for file routing `pattern` and `path` both empty
- Allow absolute path for `mydumper.files.path`, convert it to the relative path at `config.Adjust`

close #469 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

File: lightning/mydump/router_test.go [hunk 1]
```diff
@@ -40,6 +40,44 @@ func (t *testFileRouterSuite) TestRouteParser(c *C) {
 	}
 }
 
+func (t *testFileRouterSuite) TestInvalidRouteRule(c *C) {
+	rule := &config.FileRouteRule{
```
Comment (lance6716) [inline lightning/mydump/router_test.go:44]: seems be overwriten by below line

**Review by lance6716 — COMMENTED** [review]
rest LGTM

File: lightning/mydump/router_test.go (hunk 1 above)
Comment (glorv) [reply lightning/mydump/router_test.go:44]: yes, this line should be removed

File: lightning/config/config.go [hunk 2]
```diff
@@ -479,6 +479,23 @@ func (cfg *Config) Adjust() error {
 		}
 	}
 
+	// adjust file routing
+	for _, rule := range cfg.Mydumper.FileRouters {
+		if rule.Path != "" {
+			if filepath.IsAbs(rule.Path) {
```
Comment (kennytm) [inline lightning/config/config.go:485]: the `!= ""` check is redundant since `filepath.IsAbs("")` is false on both Linux and Windows.

```suggestion
		// if rule.Path is empty, filepath.IsAbs("") is false and won't enter this branch for absolute-to-relative adjustment.
		if filepath.IsAbs(rule.Path) {
```

**Review by kennytm — COMMENTED** [review]
rest LGTM

**Review by kennytm — APPROVED** [review]
