### PR TITLE
server: check open file ulimit for local backend

### LINKED ISSUE #342: local backend error: too many open files
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
When importing massive data (2.8T, 40k warehouses tpcc data), tidb-lightning will raise error "too many open files" constantly without quit.

2. What did you expect to see?
Check the limit files before importing

3. What did you see instead?
Error "too many open files" all the time

4. Versions of the cluster

    - TiDB-Lightning version (run `tidb-lightning -V`):

        ```
        [root@localhost tidb-lightning]# ./bin/tidb-lightning -V
        Release Version: v3.0.16-2-g4af19d5
        Git Commit Hash: 4af19d5d44837d6c6fe3ba3ad191df354e310ad3
        Git Branch: master
        UTC Build Time: 2020-07-02 10:23:10
        Go Version: go version go1.13.11 linux/amd64
        ```
        
    - TiKV-Importer version (run `tikv-importer -V`)

        ```
        (paste TiKV-Importer version here)
        ```
        
    - TiKV version (run `tikv-server -V`):

        ```
        (paste TiKV version here)
        ```

    - TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        (paste TiDB cluster version here)
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. Operation logs
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs
   
6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `inventory.ini` if deployed by Ansible

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for TiDB-Lightning if possible

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Check process max open file limit for local backend

### What is changed and how it works?
In local backend mode, pebble need to write a lot of L0 sst files. So If data source is fairly big, the max_open_file limit may not be enough. So we check the `RLIMIT_NOFILE` base on source file size, and try to update it if not big enough.

close #342 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

Related changes

### CODE REVIEW

File: cmd/tidb-lightning/main.go [hunk 1]
```diff
@@ -96,3 +105,47 @@ func main() {
 		os.Exit(1)
 	}
 }
+
+func checkSystemRequirement(cfg *config.GlobalConfig) error {
```
Comment (kennytm) [inline cmd/tidb-lightning/main.go:109]: (1) This should be checked using the task config before every task starts
(2) This should be ignorable using `--check-requirements=false`

File: cmd/tidb-lightning/main.go [hunk 2]
```diff
@@ -96,3 +105,47 @@ func main() {
...
+		}
+		if rLimit.Max < estimateMaxFiles {
+			// If the process is not started by privileged user, this will fail.
+			rLimit.Max = estimateMaxFiles
+		}
+		prevLimit := rLimit.Cur
+		rLimit.Cur = estimateMaxFiles
+		err = syscall.Setrlimit(syscall.RLIMIT_NOFILE, &rLimit)
+		if err != nil {
+			return errors.Wrap(err, fmt.Sprintf("the maximum number of open file descriptors is too small, got %d, expect greater or equal to %d", prevLimit, estimateMaxFiles))
```
Comment (kennytm) [inline cmd/tidb-lightning/main.go:146]:
```suggestion
			return errors.Annotatef(err, "the maximum number of open file descriptors is too small, got %d, expect greater or equal to %d", prevLimit, estimateMaxFiles)
```

File: cmd/tidb-lightning/main.go [hunk 3]
```diff
@@ -96,3 +105,47 @@ func main() {
...
+			}
+			return err
+		})
+		if err != nil {
+			return errors.Trace(err)
+		}
+
+		// we estimate each sst as 50MB, this is a fairly coarse predict, the actual fd needed is
+		// depend on chunk&import concurrency and each data&index key-value size
+		estimateMaxFiles := totalSize / (50 * 1024 * 1024)
```
Comment (kennytm) [inline cmd/tidb-lightning/main.go:129]: how this "50 MiB" is determined? 

also, for a 10 TB data set this means Pebble will open up to 200000 files simultaneously. This sounds more like a bug to me (that the engines are not closed quickly enough).

Comment (glorv) [reply cmd/tidb-lightning/main.go:129]: In the tpcc benchmaerk, with a memtable size of 512MB, the generated L0 sst file sizes ranges from 40~450MB, so I'm not sure how to estimate the avg size. And In the common case, L0 sst files will be compressed to L1~Ln level ssts, thus total files should be very large, but we prevent the compression phase in favor of better performance thus the generated files numbers will be quite big. Because index engine can't be split, so if a table is huge, and there are many indices, then maybe we will generate thousands of L0 sst files.

Comment (kennytm) [reply cmd/tidb-lightning/main.go:129]: can we use the largest N total size of each table (N = index concurrency) instead of the entire data source?

from the pebble source code it seems 50 MiB = [25](https://github.com/cockroachdb/pebble/blob/a452ae2c916a74a035d264e42c9b761061a988b5/compaction.go#L41) × [2 MiB](https://github.com/cockroachdb/pebble/blob/a452ae2c916a74a035d264e42c9b761061a988b5/options.go#L225), so maybe we could increase the TargetFileSize? 🤔 In TiKV Importer [this is set](https://github.com/tikv/importer/blob/9531815ad95fac8dc6febcf0fb8cd76d01662df3/src/import/engine.rs#L385) to [1 GiB](https://github.com/tikv/importer/blob/9531815ad95fac8dc6febcf0fb8cd76d01662df3/etc/tikv-importer.toml#L23).

Comment (glorv) [reply cmd/tidb-lightning/main.go:129]: Seems the L0 sst file size is depend on the memory table size and the conf `MaxOpenFiles` is used for compaction. After explict set `MaxOpenFiles` option to 1GB, the table `order_line` index engine still generates a lots of sst files with size of 54MB. And almost each engine generates sst files with different size.  Maybe we should use `MemoryTableSize` as each sst file's size, as memory table accounts for the raw size of the kv-pairs.
So we can estimate by:  {top N table size} / {MemoryTableSize} as the needed fds

Comment (kennytm) [reply cmd/tidb-lightning/main.go:129]: Okay.

File: lightning/lightning_test.go [hunk 4]
```diff
@@ -399,3 +401,63 @@ func (s *lightningServerSuite) TestHTTPAPIOutsideServerMode(c *C) {
...
+				},
+				{
+					TotalSize: 150_000 << 20, //200_000MB
+				},
+			},
+		},
+		{
+			Tables: []*mydump.MDTableMeta{
+				{
+					TotalSize: 150_800 << 20, //150_288MB
```
Comment (kennytm) [inline lightning/lightning_test.go:424]: not sure what these comments mean but the numbers looks way off.

**Comment by kennytm** [comment]
Blocked by #348.
