### PR TITLE
mydumper: convert parquet columns to lower case

### LINKED ISSUE #480: lightning failed to import parquet file if table column name contains upper case character
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
use lightning to load some parquet files from s3. lightning failed with following errors:
```
[2020/11/17 12:27:25.487 +00:00] [INFO] [restore.go:1932] ["restore file start"] [table=`parquet`.`usertable`] [engineNumber=0] [fileIndex=1] [path=uuid-384g0-aurora-parquet/uuid-384g-aurora/test/test.usertable/10/part-00000-1d2efb15-46b7-4e2b-9d9e-81f5209dac0d-c000.gz.parquet:0]
[2020/11/17 12:27:25.630 +00:00] [ERROR] [restore.go:1083] ["encode kv data and write failed"] [table=`parquet`.`usertable`] [engineNumber=0] [takeTime=3.408112523s] [error="unknown columns in header [YCSB_KEY strikerUserCharacterId myStrikerUserCharacterId staminaModifiedAt hotSpotStamina hotSpotStaminaModifiedAt characterCapacity extendedCharacterCapacity drewTutorialGacha isTutorialEnd medalId noun1TitleId conjunctionTitleId noun2TitleId lointAt lastLoginBonusAt]"]
[2020/11/17 12:27:25.630 +00:00] [ERROR] [restore.go:931] ["restore engine failed"] [table=`parquet`.`usertable`] [engineNumber=0] [takeTime=3.408216608s] [error="unknown columns in header [YCSB_KEY strikerUserCharacterId myStrikerUserCharacterId staminaModifiedAt hotSpotStamina hotSpotStaminaModifiedAt characterCapacity extendedCharacterCapacity drewTutorialGacha isTutorialEnd medalId noun1TitleId conjunctionTitleId noun2TitleId lointAt lastLoginBonusAt]"]
[2020/11/17 12:27:25.767 +00:00] [INFO] [restore.go:1932] ["restore file start"] [table=`parquet`.`usertable`] [engineNumber=1] [fileIndex=1] [path=uuid-384g0-aurora-parquet/uuid-384g-aurora/test/test.usertable/2878/part-00000-b8d4a4d2-f56a-4e4c-a48b-f32738272309-c000.gz.parquet:0]
[2020/11/17 12:27:25.884 +00:00] [ERROR] [restore.go:1083] ["encode kv data and write failed"] [table=`parquet`.`usertable`] [engineNumber=1] [takeTime=3.662541533s] [error="unknown columns in header [YCSB_KEY strikerUserCharacterId myStrikerUserCharacterId staminaModifiedAt hotSpotStamina hotSpotStaminaModifiedAt characterCapacity extendedCharacterCapacity drewTutorialGacha isTutorialEnd medalId noun1TitleId conjunctionTitleId noun2TitleId lointAt lastLoginBonusAt]"]
[2020/11/17 12:27:25.884 +00:00] [ERROR] [restore.go:931] ["restore engine failed"] [table=`parquet`.`usertable`] [engineNumber=1] [takeTime=3.662656037s] [error="unknown columns in header [YCSB_KEY strikerUserCharacterId myStrikerUserCharacterId staminaModifiedAt hotSpotStamina hotSpotStaminaModifiedAt characterCapacity extendedCharacterCapacity drewTutorialGacha isTutorialEnd medalId noun1TitleId conjunctionTitleId noun2TitleId lointAt lastLoginBonusAt]"]
[2020/11/17 12:27:25.884 +00:00] [ERROR] [restore.go:953] ["import whole table failed"] [table=`parquet`.`usertable`] [takeTime=3.662745594s] [error="unknown columns in header [YCSB_KEY strikerUserCharacterId myStrikerUserCharacterId staminaModifiedAt hotSpotStamina hotSpotStaminaModifiedAt characterCapacity extendedCharacterCapacity drewTutorialGacha isTutorialEnd medalId noun1TitleId conjunctionTitleId noun2TitleId lointAt lastLoginBonusAt]"]
[2020/11/17 12:27:25.884 +00:00] [ERROR] [restore.go:693] ["restore table failed"] [table=`parquet`.`usertable`] [takeTime=53m47.021028337s] [error="restore table `parquet`.`usertable` failed: unknown columns in header [YCSB_KEY strikerUserCharacterId myStrikerUserCharacterId staminaModifiedAt hotSpotStamina hotSpotStaminaModifiedAt characterCapacity extendedCharacterCapacity drewTutorialGacha isTutorialEnd medalId noun1TitleId conjunctionTitleId noun2TitleId lointAt lastLoginBonusAt]"]
```

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Convert parquet reader columns to lower case to be compatible with other logics involving the column names

close #480 

### Check List 

Tests 

 - Unit test
 - Integration test
 - No code

Side effects

Related changes

### CODE REVIEW

File: lightning/mydump/parquet_parser.go [hunk 1]
```diff
@@ -89,7 +90,7 @@ func NewParquetParser(
 	for i, c := range reader.SchemaHandler.SchemaElements {
 		if c.GetNumChildren() == 0 {
 			// the SchemaElement.Name is capitalized, we should use the original name
-			columns = append(columns, reader.SchemaHandler.Infos[i].ExName)
+			columns = append(columns, strings.ToLower(reader.SchemaHandler.Infos[i].ExName))
```
Comment (kennytm) [inline lightning/mydump/parquet_parser.go:93]: is the comment "the SchemaElement.Name is capitalized, we should use the original name" still relevant since we're always using `ToLower` here

Comment (glorv) [reply lightning/mydump/parquet_parser.go:93]: yes, in this way there is no difference between these two fields.

Comment (kennytm) [reply lightning/mydump/parquet_parser.go:94]: i mean if they are the same we could simplify the loop to 

```go
for _, c := range reader.SchemaHandler.SchemaElements {
    if c.GetNumChildren() == 0 {
        columns = append(columns, strings.ToLower(c.Name))
```

**Review by kennytm — COMMENTED** [review]
lgtm

**Review by lance6716 — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
I guess there won't be a parquet has column both `a` and `A`?
